version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:jdbc: mariadb://project3.chow0wcw2ldz.us-west-1.rds.amazonaws.com:3306/pantryDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: project3backend
